In [1]:
import pandas as pd

In [41]:
df=pd.read_csv('drug200.csv')
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [43]:
from sklearn.preprocessing import LabelEncoder

In [44]:
le_Sex = LabelEncoder()
df['Sex'] = le_Sex.fit_transform(df['Sex'])
le_BP = LabelEncoder()
df['BP'] = le_BP.fit_transform(df['BP'])
le_Cholesterol = LabelEncoder()
df['Cholesterol'] = le_Cholesterol.fit_transform(df['Cholesterol'])
le_Drug = LabelEncoder()
df['Drug'] = le_Drug.fit_transform(df['Drug'])

df.head(6)

   Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   0            0   25.355     0
1   47    1   1            0   13.093     3
2   47    1   1            0   10.114     3
3   28    0   2            0    7.798     4
4   61    0   1            0   18.043     0
5   22    0   2            0    8.607     4

In [13]:
input = df.drop('Drug',axis='columns')
target = df['Drug']

In [61]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(input)

In [62]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_scaled,target,test_size=0.2)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [63]:
lr = LogisticRegression(max_iter=10000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.875

In [64]:
svm=SVC(max_iter=10000)
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.8

In [65]:
dt=DecisionTreeClassifier()
dt.fit(x_train, y_train)
dt.score(x_test, y_test)

1.0

In [66]:
rf=RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.975

In [67]:
nb=GaussianNB()
nb.fit(x_train, y_train)
nb.score(x_test, y_test)

0.925

In [23]:
from sklearn.model_selection import cross_val_score

In [68]:
lr_scores=cross_val_score(LogisticRegression(solver='liblinear', max_iter=1000), input, target,cv=3)
lr_scores

array([0.79104478, 0.82089552, 0.81818182])

In [70]:
dt_scores = cross_val_score(DecisionTreeClassifier(), input, target, cv=3)
dt_scores

array([1.        , 1.        , 0.96969697])

In [71]:
svm_scores = cross_val_score(SVC(), input, target, cv=3)
svm_scores

array([0.71641791, 0.70149254, 0.6969697 ])

In [72]:
rf_scores = cross_val_score(RandomForestClassifier(), input, target, cv=3)
rf_scores

array([1.        , 1.        , 0.96969697])

In [73]:
nb_scores = cross_val_score(GaussianNB(), input, target, cv=3)
nb_scores

array([0.85074627, 0.89552239, 0.86363636])

In [74]:
print("Logistic Regression Scores:", cross_val_score(LogisticRegression(solver='liblinear', max_iter=1000), input, target,cv=3))
print("Decision Tree Scores:", dt_scores)
print("SVM Scores:", svm_scores)
print("Random Forest Scores:", rf_scores)
print("Naive Bayes Scores:", nb_scores)

Logistic Regression Scores: [0.79104478 0.82089552 0.81818182]
Decision Tree Scores: [1.         1.         0.96969697]
SVM Scores: [0.71641791 0.70149254 0.6969697 ]
Random Forest Scores: [1.         1.         0.96969697]
Naive Bayes Scores: [0.85074627 0.89552239 0.86363636]

In [75]:
y_test[:10]

34     4
193    3
155    3
179    0
50     0
7      3
66     1
89     0
62     0
87     0
Name: Drug, dtype: int64

In [76]:
lr.predict(x_test[:10])

array([4, 2, 3, 0, 0, 3, 1, 4, 0, 0])

In [77]:
svm.predict(x_test[:10])

array([0, 4, 0, 0, 0, 3, 1, 4, 0, 0])

In [78]:
dt.predict(x_test[:10])

array([4, 3, 3, 0, 0, 3, 1, 0, 0, 0])

In [79]:
rf.predict(x_test[:10])

array([4, 4, 3, 0, 0, 3, 1, 0, 0, 0])

In [80]:
nb.predict(x_test[:10])

array([4, 3, 3, 0, 2, 3, 1, 0, 0, 3])

In [102]:
input.shape

(200, 5)

using Pca to reduce dimensions

In [100]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
X_pca = pca.fit_transform(input)
X_pca.shape

(200, 2)

In [85]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, target, test_size=0.2, random_state=30)

In [87]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train_pca, y_train)
lr.score(X_test_pca, y_test)

0.625

In [88]:
rf=RandomForestClassifier()
rf.fit(X_train_pca, y_train)
rf.score(X_test_pca, y_test)

0.675

In [89]:
dt=DecisionTreeClassifier()
dt.fit(X_train_pca, y_train)
dt.score(X_test_pca, y_test)
#

0.65

In [90]:
svm=SVC()
svm.fit(X_train_pca, y_train)
svm.score(X_test_pca, y_test)

0.725

In [91]:
nb=GaussianNB()
nb.fit(X_train_pca, y_train)
nb.score(X_test_pca, y_test)

0.75

In [93]:
y_test[:10]

143    0
81     4
26     0
150    1
124    2
24     0
126    0
142    2
129    4
171    4
Name: Drug, dtype: int64

In [95]:
lr.predict(X_test_pca[:10])

array([0, 4, 0, 4, 4, 0, 0, 4, 4, 4])

In [96]:
dt.predict(X_test_pca[:10])

array([0, 4, 0, 4, 4, 0, 0, 4, 4, 4])

In [103]:
rf.predict(X_test_pca[:10])

array([0, 4, 0, 4, 4, 0, 0, 4, 4, 4])

In [104]:
svm.predict(X_test_pca[:10])

array([0, 4, 0, 4, 4, 0, 0, 4, 4, 4])

In [105]:
nb.predict(X_test_pca[:10])

array([0, 4, 0, 4, 4, 0, 0, 4, 4, 4])