In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('mushrooms.csv')
df

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [140]:
from sklearn.preprocessing import LabelEncoder

In [15]:
for column in df.columns:
    if df[column].dtype == 'object':
        le = LabelEncoder()
        df[column] = le.fit_transform(df[column])

df.head(6)

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,7,7,0,2,1,0,3,0,1
5,0,5,3,9,1,0,1,0,0,5,...,2,7,7,0,2,1,4,2,2,1

In [16]:
input = df.drop('class',axis='columns')
target = df['class']

In [132]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input,target,test_size=0.3,)

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [141]:
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9511894995898277

In [142]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
dt.score(x_test, y_test)

1.0

In [143]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9897456931911403

In [144]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

1.0

In [145]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [146]:
nb.fit(x_train, y_train)
nb.score(x_test, y_test )

0.920836751435603

In [74]:
from sklearn.model_selection import cross_val_score

In [103]:
cross_val_score(LogisticRegression(solver='liblinear', max_iter=1000), input, target,cv=3)

array([0.6894387 , 0.91802068, 0.83567208])

In [104]:
dt_scores = cross_val_score(DecisionTreeClassifier(), input, target, cv=3)
dt_scores

array([0.90251108, 0.99113737, 0.73855244])

In [105]:
svm_scores = cross_val_score(SVC(), input, target, cv=3)
svm_scores

array([0.71971935, 0.92577548, 0.69940916])

In [78]:
rf_scores = cross_val_score(RandomForestClassifier(), input, target, cv=3)
rf_scores

array([0.90546529, 0.99335303, 0.73412112])

In [106]:
nb_scores = cross_val_score(GaussianNB(), input, target, cv=3)
nb_scores

array([0.7422452 , 0.80169867, 0.74446086])

In [107]:
print("Logistic Regression Scores:", cross_val_score(LogisticRegression(solver='liblinear', max_iter=1000), input, target,cv=3))
print("Decision Tree Scores:", dt_scores)
print("SVM Scores:", svm_scores)
print("Random Forest Scores:", rf_scores)
print("Naive Bayes Scores:", nb_scores)

Logistic Regression Scores: [0.6894387  0.91802068 0.83567208]
Decision Tree Scores: [0.90251108 0.99113737 0.73855244]
SVM Scores: [0.71971935 0.92577548 0.69940916]
Random Forest Scores: [0.90546529 0.99335303 0.73412112]
Naive Bayes Scores: [0.7422452  0.80169867 0.74446086]

In [134]:
y_test[:10]

5789    1
777     0
640     0
1390    0
6486    1
7646    1
4310    1
1785    0
7799    1
8095    1
Name: class, dtype: int64

In [135]:
lr.predict(x_test[:10])

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 0])

In [136]:
dt.predict(x_test[:10])

array([1, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [137]:
svm.predict(x_test[:10])

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [138]:
rf.predict(x_test[:10])

array([1, 0, 0, 0, 1, 1, 1, 0, 1, 1])

In [139]:
nb.predict(x_test[:10])

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 0])

Decision tree and Random forest are giving the most accurate predictions for the given dataset